### ISSUE TITLE
Add Combobox accessibility functionality

### ISSUE THREAD

**Issue by iseth** [PhlexUI/rbui#64]
This issue is to propose an enhancement for the combobox. It consists of two main changes:

1. **Add Keyboard Support** - Extend the combobox functionality to support `ctrl+n` and `ctrl+p` key combinations, functioning similarly to the up and down arrows. This would provide a smoother and more intuitive user experience. (Suggested by @iseth)

2. **Focus Management** - Adjust how focus is handled with the combobox. Currently, when the combobox is focused and opened, closing it with the `ESC` key also removes focus from the combobox. The proposed behavior is that the `ESC` key should only close the combobox, still maintaining its focus. This would allow the user to reopen the combobox with either `CR` or `SPACE`, or proceed to the next element with the `TAB` key. (Suggested by @cirdes)

I believe these enhancements will significantly improve user interaction with the combobox.

**Comment by cirdes** [comment]
@iseth, I'm closing this issue because Ctrl+N and Ctrl+P are not mandatory for the combobox, and the vast majority of keyboard shortcuts have been added. Additionally, the focus issue has been fixed.

Feel free to reopen it if needed.
